using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace VagrantStoryArchipelago.Helpers
{
    public class ItemHelper
    {
        public Dictionary<byte, string> ItemReference = new Dictionary<byte, string>() {
            { 0x43, "Cure Root" },
            { 0x44, "Cure Bulb" },
            { 0x45, "Cure Tonic" },
            { 0x46, "Cure Potion" },
            { 0x47, "Mana Root" },
            { 0x48, "Mana Bulb" },
            { 0x49, "Mana Tonic" },
            { 0x4A, "Mana Potion" },
            { 0x4B, "Vera Root" },
            { 0x4C, "Vera Bulb" },
            { 0x4D, "Vera Tonic" },
            { 0x4E, "Vera Potion" },
            { 0x4F, "Acolyte´s Nostrum" },
            { 0x50, "Saint´s Nostrum" },
            { 0x51, "Alchemist´s Reagent" },
            { 0x52, "Sorcerer´s Reagent" },
            { 0x53, "Yggdrasill´s Tears" },
            { 0x54, "Faerie Chortle" },
            { 0x55, "Spirit Orison" },
            { 0x56, "Angelic Paean" },
            { 0x57, "Panacea" },
            { 0x58, "Snowfly Draught" },
            { 0x59, "Faerie Wing" },
            { 0x5A, "Elixir of Kings" },
            { 0x5B, "Elixir of Sages" },
            { 0x5C, "Elixir of Dragons" },
            { 0x5D, "Elixir of Queens" },
            { 0x5E, "Elixir of Mages" },
            { 0x5F, "Valens (Wine)" },
            { 0x60, "Prudens (Wine)" },
            { 0x61, "Volare (Wine)" },
            { 0x62, "Audentia (Wine)" },
            { 0x63, "Virtus (Wine)" },
            { 0x64, "Eye of Argon" },
            { 0x82, "Grimoire Zephyr" },
            { 0x83, "Grimoire Teslae" },
            { 0x84, "Grimoire Incendie" },
            { 0x85, "Grimoire Terre" },
            { 0x86, "Grimoire Glace" },
            { 0x87, "Grimoire Lux" },
            { 0x88, "Grimoire Patir" },
            { 0x89, "Grimoire Exsorcer" },
            { 0x8A, "Grimoire Banish" },
            { 0x8B, "Grimoire Demolir" },
            { 0x93, "Grimoire Flamme" },
            { 0x97, "Grimoire Gaea" },
            { 0x9B, "Grimoire Avalanche" },
            { 0x9F, "Grimoire Radius" },
            { 0xA1, "Grimoire Meteore" },
            { 0xA7, "Grimoire Egout" },
            { 0xA8, "Grimoire Demance" },
            { 0xA9, "Grimoire Guerir" },
            { 0xAA, "Grimoire Mollesse" },
            { 0xAB, "Grimoire Antidote" },
            { 0xAC, "Grimoire Benir" },
            { 0xAD, "Grimoire Purifier" },
            { 0xAE, "Grimoire Vie" },
            { 0xAF, "Grimoire Intensite" },
            { 0xB0, "Grimoire Debile" },
            { 0xB1, "Grimoire Eclairer" },
            { 0xB2, "Grimoire Nuageux" },
            { 0xB3, "Grimoire Agilite" },
            { 0xB4, "Grimoire Tardif" },
            { 0xB5, "Grimoire Ameliorer" },
            { 0xB6, "Grimoire Deterior" },
            { 0xB7, "Grimoire Muet" },
            { 0xB8, "Grimoire Annuler" },
            { 0xB9, "Grimoire Paralysie" },
            { 0xBA, "Grimoire Venin" },
            { 0xBB, "Grimoire Fleau" },
            { 0xBC, "Grimoire Halte" },
            { 0xBD, "Grimoire Dissiper" },
            { 0xBE, "Grimoire Clef" },
            { 0xBF, "Grimoire Visual" },
            { 0xC0, "Grimoire Snalyse" },
            { 0xC1, "Grimoire Sylphe" },
            { 0xC2, "Grimoire Salamander" },
            { 0xC3, "Grimoire Gnome" },
            { 0xC4, "Grimoire Undine" },
            { 0xC5, "Grimoire Parebrise" },
            { 0xC6, "Grimoire Ignifuge" },
            { 0xC7, "Grimoire Rempart" },
            { 0xC8, "Grimoire Barrer" },
            { 0xCA, "Bronze Key" },
            { 0xCB, "Iron Key" },
            { 0xCC, "Silver Key" },
            { 0xCD, "Gold Key" },
            { 0xCE, "Platinum Key" },
            { 0xCF, "Steel Key" },
            { 0xD0, "Crimson Key" },
            { 0xD1, "Chest Key" },
            { 0xD2, "Chamomile Sigil" },
            { 0xD3, "Lily Sigil" },
            { 0xD4, "Tearose Sigil" },
            { 0xD5, "Clematis Sigil" },
            { 0xD6, "Hyacinth Sigil" },
            { 0xD7, "Fern Sigil" },
            { 0xD8, "Aster Sigil" },
            { 0xD9, "Eulelia Sigil" },
            { 0xDA, "Melissa Sigil" },
            { 0xDB, "Calla Sigil" },
            { 0xDC, "Laurel Sigil" },
            { 0xDD, "Acacia Sigil" },
            { 0xDE, "Palm Sigil" },
            { 0xDF, "Kalmia Sigil" },
            { 0xE0, "Colombine Sigil" },
            { 0xE1, "Anemone Sigil" },
            { 0xE2, "Verbena Sigil" },
            { 0xE3, "Schirra Sigil" },
            { 0xE4, "Marigold Sigil" },
            { 0xE5, "Azalea Sigil" },
            { 0xE6, "Tigertail Sigil" },
            { 0xE7, "Stock Sigil" },
            { 0xE8, "Cattleya Sigil" },
            { 0xE9, "Mandrake Sigil" }
        };
    }
}
