using Archipelago.Core.Models;
using VagrantStoryArchipelago;
using VagrantStoryArchipelago.Models;

namespace Helpers
{
    public class LocationHelpers
    {
        // buildLocationsList returns a list of all the valid locations that you need to read from the game
        // while also taking into account what the addresses have to match in order to send out a location.
        // the ID's here must match the ID's in your ap world.

        // It helps to split them out somewhere that you can import and loop over instead of doing them one at a time like this. If you have regions in your ap world
        // then that's a great way to split them up. Just a reminder, the important thing is THAT THE ID'S MATCH THE APWORLD.
        public static List<ILocation> BuildLocationList(Dictionary<string, object> options)
        {



            int base_id = 99350000;
            int region_offset = 1000;

            //int gargoyleSanity = int.Parse(options?.GetValueOrDefault("gargoylesanity", "0").ToString());
            //int bookSanity = int.Parse(options?.GetValueOrDefault("booksanity", "0").ToString());

            List<string> table_order = [
                "Ashley",
                "Prologue",
                "Entrance to Darkness",
                "Worker's Breakroom",
                "Hall of Struggle",
                "Smokebarrel Stair",
                "Wine Guild Hall",
                "Wine Magnate's Chambers",
                "Fine Vintage Vault",
                "Chamber of Fear",
                "The Reckoning Room",
                "A Laborer's Thirst",
                "The Rich Drown in Wine",
                "Room of Rotten Grapes",
                "Blackmarket of Wines",
                "The Gallows",
                "Room of Cheap Red Wine",
                "Room of Cheap White Wine",
                "The Greedy One's Den",
                "The Hero's Winehall",
                "The Bread Peddler's Way",
                "Way of the Mother Lode",
                "Sewer of Ravenous Rats",
                "Underdark Fishmarket",
                "The Sunless Way",
                "Remembering Days of Yore",
                "Larder for a Lean Winter",
                "Where the Hunter Climbed",
                "Hall of Poverty",
                "The Washing-Woman's Way",
                "Nameless Dark Oblivion",
                "Sinner's Corner",
                "Fear of the Fall",
                "The Children's Hideout",
                "Corner of Prayers",
                "Hope Obstructed",
                "Beggars of the Mouthharp",
                "Corner of the Wretched",
                "Crossroads of Rest",
                "Path to the Greengrocer",
                "Path of the Children",
                "Salvation for the Mother",
                "The Body Fragile Yields",
                "Bite the Master's Wounds",
                "Workshop 'Godhands'",
                "The Crumbling Market (South)",
                "The Crumbling Market (North)",
                "Where Flood Waters Ran",
                "Tears from Empty Sockets",
                "Hall to a New World",
                "Place of Free Words",
                "Bazaar of the Bizarre",
                "Noble Gold and Silk",
                "Weapons Not Allowed",
                "A Knight Sells his Sword",
                "Gemsword Blackmarket",
                "The Pirate's Son",
                "Sale of the Sword",
                "The Greengrocer's Stair",
                "Where Black Waters Ran",
                "Arms Against Invaders",
                "Catspaw Blackmarket",
                "Forcas Rise",
                "Valdiman Gates",
                "Rue Aliano",
                "The House Khazabas",
                "Zebel's Walk",
                "Rue Volnac",
                "Rue Faltes",
                "Rue Morgue",
                "Rue Lejour",
                "Kesch Bridge",
                "Rue Crimnade",
                "Workshop 'Junction Point'",
                "Rue Fisserano",
                "Workshop 'Metal Works'",
                "Shasras Hill Park",
                "The House Gilgitte",
                "Gharmes Walk",
                "Plateia Lumitar",
                "Rue Vermillion",
                "The Rene Coastroad",
                "Workshop 'Magic Hammer'",
                "Rue Mal Fallde",
                "Tircolas Flow (North)",
                "Tircolas Flow (South)",
                "Rue Bouquet",
                "Glacialdra Kirk Ruins",
                "Rue Sant D'alsa",
                "Dinas Walk",
                "Villeport Way",
                "The Soldier's Bedding",
                "A Storm of Arrows",
                "Time Trial (Minotaur)",
                "Time Trial (Dragon)",
                "Urge the Boy On",
                "Time Trial (Earth Dragon)",
                "Time Trial (Snow Dragon)",
                "A Taste of the Spoils",
                "Time Trial (Damascus Golem)",
                "Time Trial (Damascus Crab)",
                "Wiping Blood from Blades",
                "Time Trial (Death + Ogre Zombie)",
                "Time Trial (Asura)",
                "The Warrior's Rest",
                "Workshop 'Keane's Crafts'",
                "The Dark Coast",
                "Hall of Prayer",
                "Those who Drink the Dark",
                "The Chapel of Meschaunce",
                "The Resentful Ones",
                "Those who Fear the Light",
                "Chamber of Reason",
                "Exit to City Center",
                "The Faerie Circle",
                "The Hunt Begins",
                "Which Way Home",
                "The Giving Trees",
                "The Birds and the Bees",
                "The Wounded Boar",
                "Golden Egg Way",
                "Traces of the Beast",
                "Fluttering Hope",
                "Return to the Land",
                "The Yellow Wood",
                "They Also Feed",
                "The Spirit Trees",
                "Where Soft Rains Fell",
                "Forest River",
                "Lamenting to the Moon",
                "Running with the Wolves",
                "You Are the Prey",
                "The Secret Path",
                "Hewn from Nature",
                "The Wood Gate",
                "The Wolves' Choice",
                "The Woodcutter's Run",
                "The Hollow Hills",
                "Howl of the Wolf King",
                "The Silent Hedges",
                "Steady the Boar-Spears",
                "The Boar's Revenge",
                "Nature's Womb",
                "Prisoners' Niche",
                "Corridor of the Clerics",
                "Priests' Confinement",
                "Alchemists' Laboratory",
                "The Academia Corridor",
                "Theology Classroom",
                "Shrine of the Martyrs",
                "Hallowed Hope",
                "Hall of Sacrilege",
                "Advent Ground (South)",
                "Passage of the Refugees (South)",
                "Passage of the Refugees (North)",
                "Advent Ground (North)",
                "The Cleansing Chantry",
                "Stairway to the Light",
                "Dark Abhors Light",
                "Dream of the Holy Land",
                "The Ore Road",
                "The Air Stirs",
                "Bonds of Friendship",
                "Atone for Eternity",
                "Stair to Sanctuary",
                "The Fallen Hall",
                "The Rotten Core",
                "The Dreamer's Climb",
                "The Ore-Bearers",
                "Screams of the Wounded",
                "Bacchus is Cheap",
                "Sinner's Sustenence",
                "The Timely Dew of Sleep",
                "Companions in Arms",
                "The Auction Block",
                "Ascension",
                "Where the Serpent Hunts",
                "Drowned in Fleeting Joy",
                "Ants Prepare for Winter",
                "The Laborer's Bonfire",
                "Stone and Sulfurous Fire",
                "Torture Without End",
                "Way Down",
                "Excavated Hollow",
                "Parting Regrets",
                "Corridor of Tales",
                "Dust Shall Eat the Days",
                "Hall of the Wage-Paying",
                "Tunnel of the Heartless",
                "The Cage",
                "The Cauldron",
                "Wooden Horse",
                "Starvation",
                "The Breast Ripper",
                "The Wheel",
                "The Branks",
                "The Pear",
                "The Judas Cradle",
                "The Whirlygig",
                "Spanish Tickler",
                "Heretic's Fork",
                "The Chair of Spikes",
                "Blooding",
                "Bootikens",
                "Burial",
                "Burning",
                "Cleansing the Soul",
                "The Ducking Stool",
                "The Garotte",
                "Hanging",
                "Impalement",
                "Knotting",
                "The Eunics' Lot",
                "Ordeal By Fire",
                "The Oven at Neisse",
                "Pressing",
                "The Mind Burns",
                "The Rack",
                "The Saw",
                "The Cold's Bridle",
                "The Shin-Vice",
                "The Spider",
                "Lead Sprinkler",
                "Squassation",
                "The Strappado",
                "Thumbscrews",
                "Pendulum",
                "Dragging",
                "Strangulation",
                "Tablillas",
                "Tongue Slicer",
                "Ordeal by Water",
                "Brank",
                "Tormentum Insomniae",
                "The Iron Maiden",
                "Judgement",
                "Saint Elmo's Belt",
                "Dunking the Witch",
                "Into Holy Battle",
                "The Poisoned Chapel",
                "Sin and Punishment",
                "A Light in the Dark",
                "Monk's Leap",
                "Hieratic Recollections",
                "The Flayed Confessional",
                "Cracked Pleasures",
                "Where Darkness Spreads",
                "Struggle for the Soul",
                "Order and Chaos",
                "An Offering of Souls",
                "Truth and Lies",
                "Sanity and Madness",
                "The Victor's Laurels",
                "Free from Base Desires",
                "Abasement from Above",
                "The Convent Room",
                "The Hall of Broken Vows",
                "Light and Dark Wage War",
                "An Arrow into Darkness",
                "He Screams for Mercy",
                "The Acolyte's Weakness",
                "Maelstrom of Malice",
                "The Melodics of Madness",
                "What Ails You, Kills You",
                "The Wine-Lecher's Fall",
                "The Heretics' Story (Lower)",
                "The Heretics' Story (Upper)",
                "Despair of the Fallen",
                "Hopes of the Idealist",
                "Where the Soul Rots",
                "The Atrium",
                "Dome",
                "Paling",
                "Stair to the Sinners",
                "Slaughter of the Innocent",
                "The Oracle Sins No More",
                "The Fallen Knight",
                "Awaiting Retribution",
                "Shelter From the Quake",
                "Buried Alive",
                "Movement of Fear",
                "Facing Your Illusions",
                "The Darkness Drinks",
                "Fear and Loathing",
                "Blood and The Beast",
                "Where Body and Soul Part",
                "Students of Death",
                "The Gabled Hall",
                "Where the Master Fell",
                "In Wait of the Foe",
                "Swords for the Land",
                "The Weeping Boy",
                "Where Weary Riders Rest",
                "The Boy's Training Room",
                "From Squire to Knight",
                "Traces of Invasion Past",
                "Be for Battle Prepared",
                "Destruction and Rebirth",
                "From Boy to Hero",
                "A Welcome Invasion",
                "Train and Grow Strong",
                "The Squire's Gathering",
                "The Invaders are Found",
                "The Dream Weavers",
                "The Cornered Savage",
                "Hall of Sworn Revenge",
                "The Last Blessing",
                "The Weeping Corridor",
                "Persecution Hall",
                "Rodent-Ridden Chamber",
                "Shrine to the Martyrs",
                "The Lamenting Mother (West)",
                "The Lamenting Mother (East)",
                "Hall of Dying Hope",
                "Bandits' Hideout",
                "The Bloody Hallway",
                "Faith Overcame Fear",
                "The Withered Spring",
                "Workshop 'Work of Art'",
                "Repent, O ye Sinners",
                "The Reaper's Victims",
                "The Last Stab of Hope",
                "Hallway of Heroes",
                "The Beast's Domain",
                "Dreamers' Entrance",
                "The Crossing",
                "Miners' Resting Hall",
                "Conflict and Accord",
                "The End of the Line",
                "The Earthquake's Mark",
                "Coal Mine Storage",
                "The Suicide King",
                "The Battle's Beginning",
                "What Lies Ahead?",
                "The Fruits of Friendship",
                "The Passion of Lovers",
                "The Hall of Hope",
                "The Dark Tunnel",
                "Everwant Passage",
                "Mining Regrets",
                "Rust in Peace",
                "The Smeltry",
                "Clash of Hyaenas",
                "Greed Knows No Bounds",
                "Live Long and Prosper",
                "Pray to the Mineral Gods",
                "Traitor's Parting",
                "Escapeway",
                "Subtellurian Horrors",
                "Dining in Darkness",
                "Bandit's Hollow",
                "Delusions of Happiness",
                "Work, Then Die",
                "Rock Bottom",
                "Senses Lost",
                "The Lunatic Veins",
                "Tomb of the Reborn",
                "Fool's Gold, Fool's Loss",
                "Kilroy Was Here",
                "A Wager of Noble Gold",
                "Lambs to the Slaughter",
                "The Ore of Legend",
                "Suicidal Desires",
                "Cry of the Beast",
                "The Fallen Bricklayer",
                "Hall of Contemplation",
                "Hall of the Empty Sconce",
                "Acolyte's Burial Vault",
                "The Abandoned Catspaw",
                "Crossing of Blood",
                "Desire's Passage",
                "Way of Lost Children",
                "Hidden Resources",
                "Treaty Room",
                "The Miner's End",
                "Gambler's Passage",
                "Revelation Shaft",
                "Corridor of Shade",
                "Credits"
            ];

            List<ILocation> locations = new List<ILocation>();

            Dictionary<string, List<GenericLocationData>> allLevelLocations = new Dictionary<string, List<GenericLocationData>>();

            // Level Locations
            allLevelLocations.Add("Ashley", GetAshleyData());

            var regional_index = 0;

            foreach (var region_name in table_order.ToList())
            {

                long currentRegionBaseId = base_id + regional_index * region_offset;

                if (allLevelLocations.ContainsKey(region_name))
                {
                    // Retrieve the list of locations for the current region
                    List<GenericLocationData> regionLocations = allLevelLocations[region_name];

                    var location_index = 0;

                    foreach (var loc in regionLocations)

                    {
                        int locationId = (int)currentRegionBaseId + location_index;

                        locations.Add(new Location()
                        {
                            Id = locationId,
                            Name = loc.Name,
                            Address = loc.Address,
                            CheckType = loc.CheckType, 
                            CompareType = LocationCheckCompareType.Match, 
                            CheckValue = loc.Check
                            
                        });

                        location_index++;
                    }
                }
            }
#if DEBUG
            foreach (var loc in locations)
            {
                Console.WriteLine($"{loc.Name}, {loc.Id}");
            }
#endif
            return locations; 
        }

        private static List<GenericLocationData> GetAshleyData()
        {
            List<GenericLocationData> ashleyLocations = new List<GenericLocationData>()
            {
                new GenericLocationData("Ability: Heavy Shot", Addresses.AbilityHeavyShotUnlock, "0", "128", LocationCheckType.Byte),
                new GenericLocationData("Ability: Gain Life", Addresses.AbilityGainLifeUnlock, "0", "128", LocationCheckType.Byte),
                new GenericLocationData("Ability: Mind Assault", Addresses.AbilityMindAssaultUnlock, "0", "128", LocationCheckType.Byte),
                new GenericLocationData("Ability: Gain Magic", Addresses.AbilityGainMagicUnlock, "0", "128", LocationCheckType.Byte),
                new GenericLocationData("Ability: Raging Ache", Addresses.AbilityRagingAcheUnlock, "0", "128", LocationCheckType.Byte),
                new GenericLocationData("Ability: Mind Ache", Addresses.AbilityMindAcheUnlock, "0", "128", LocationCheckType.Byte),
                new GenericLocationData("Ability: Temper", Addresses.AbilityTemperUnlock, "0", "128", LocationCheckType.Byte),
                new GenericLocationData("Ability: Crimson Pain", Addresses.AbilityCrimsonPainUnlock, "0", "128", LocationCheckType.Byte),
                new GenericLocationData("Ability: Instill", Addresses.AbilityInstillUnlock, "0", "128", LocationCheckType.Byte),
                new GenericLocationData("Ability: Phantom Pain", Addresses.AbilityPhantomPainUnlock, "0", "128", LocationCheckType.Byte),
                new GenericLocationData("Ability: Paralysis Pulse", Addresses.AbilityParalysisPulseUnlock, "0", "128", LocationCheckType.Byte),
                new GenericLocationData("Ability: Numbing Claw", Addresses.AbilityNumbingClawUnlock, "0", "128", LocationCheckType.Byte),
                new GenericLocationData("Ability: Dulling Impact", Addresses.AbilityDullingImpactUnlock, "0", "128", LocationCheckType.Byte),
                new GenericLocationData("Ability: Snake Venom", Addresses.AbilitySnakeVenomUnlock, "0", "128", LocationCheckType.Byte),
                new GenericLocationData("Ability: Ward", Addresses.AbilityWardUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Ability: Siphon Soul", Addresses.AbilitySiphonSoulUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Ability: Reflect Magic", Addresses.AbilityReflectMagicUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Ability: Reflect Damage", Addresses.AbilityReflectDamageUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Ability: Absorb Magic", Addresses.AbilityAbsorbMagicUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Ability: Absorb Damage", Addresses.AbilityAbsorbDamageUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Ability: Impact Guard", Addresses.AbilityImpactGuardUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Ability: Wind Break", Addresses.AbilityWindBreakUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Ability: Fire Proof", Addresses.AbilityFireProofUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Ability: Terra Ward", Addresses.AbilityTerraWardUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Ability: Aqua Ward", Addresses.AbilityAquaWardUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Ability: Shadow Guard", Addresses.AbilityShadowGuardUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Ability: Demonscale", Addresses.AbilityDemonscaleUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Ability: Phantom Shield", Addresses.AbilityPhantomShieldUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Degenerate", Addresses.GrimoireDegenerateUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Psychodrain", Addresses.GrimoirePsychodrainUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Leadbones", Addresses.GrimoireLeadbonesUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Tarnish", Addresses.GrimoireTarnishUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Analyze", Addresses.GrimoireAnalyzeUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Herakles", Addresses.GrimoireHeraklesUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Enlighten", Addresses.GrimoireEnlightenUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Invigorate", Addresses.GrimoireInvigorateUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Prostasia", Addresses.GrimoireProstasiaUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Luft Fusion", Addresses.GrimoireLuftFusionUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Spark Fusion", Addresses.GrimoireSparkFusionUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Soil Fusion", Addresses.GrimoireSoilFusionUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Frost Fusion", Addresses.GrimoireFrostFusionUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Aero Guard", Addresses.GrimoireAeroGuardUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Pyro Guard", Addresses.GrimoirePyroGuardUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Terra Guard", Addresses.GrimoireTerraGuardUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Silence", Addresses.GrimoireSilenceUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Magic Ward", Addresses.GrimoireMagicWardUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Surging Balm", Addresses.GrimoireSurgingBalmUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Fixate", Addresses.GrimoireFixateUnlock, "0", "176", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Dispel", Addresses.GrimoireDispelUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Stun Cloud", Addresses.GrimoireStunCloudUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Poison Mist", Addresses.GrimoirePoisonMistUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Curse", Addresses.GrimoireCurseUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Restoration", Addresses.GrimoireRestorationUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Antidote", Addresses.GrimoireAntidoteUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Blessing", Addresses.GrimoireBlessingUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Clearance", Addresses.GrimoireClearanceUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Unlock", Addresses.GrimoireUnlockUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Eureka", Addresses.GrimoireEurekaUnlock, "0", "176", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Drain Heart", Addresses.GrimoireDrainHeartUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Drain Mind", Addresses.GrimoireDrainMindUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Heal", Addresses.GrimoireHealUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Solid Shock", Addresses.GrimoireSolidShockUnlock, "0", "192", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Lightning Bolt", Addresses.GrimoireLightningBoltUnlock, "0", "192", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Fireball", Addresses.GrimoireFireballUnlock, "0", "192", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Vulcan Lance", Addresses.GrimoireVulcanLanceUnlock, "0", "192", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Aqua Blast", Addresses.GrimoireAquaBlastUnlock, "0", "192", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Spirit Surge", Addresses.GrimoireSpiritSurgeUnlock, "0", "192", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Dark Chant", Addresses.GrimoireDarkChantUnlock, "0", "192", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Exorcism", Addresses.GrimoireExorcismUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Banish", Addresses.GrimoireBanishUnlock, "0", "144", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Explosion Max Level", Addresses.GrimoireExplosionMaxLevel, "0", "704", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Thunderburst Max Level", Addresses.GrimoireThunderburstMaxLevel, "0", "704", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Flame Sphere Max Level", Addresses.GrimoireFlameSphereMaxLevel, "0", "704", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Gaea Strike Max Level", Addresses.GrimoireGaeaStrikeMaxLevel, "0", "704", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Avalanche Max Level", Addresses.GrimoireAvalancheMaxLevel, "0", "704", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Radial Surge Max Level", Addresses.GrimoireRadialSurgeMaxLevel, "0", "704", LocationCheckType.Byte),
                new GenericLocationData("Grimoire: Meteor Max Level", Addresses.GrimoireMeteorMaxLevel, "0", "704", LocationCheckType.Byte),
                new GenericLocationData("Break: Whistle Sting", Addresses.BreakWhistleStingUnlock, "0", "192", LocationCheckType.Byte),
                new GenericLocationData("Break: Shadoweave", Addresses.BreakShadoweaveUnlock, "0", "192", LocationCheckType.Byte),
                new GenericLocationData("Break: Double Fang", Addresses.BreakDoubleFangUnlock, "0", "128", LocationCheckType.Byte),
                new GenericLocationData("Break: Wyrm Scorn", Addresses.BreakWyrmScornUnlock, "0", "160", LocationCheckType.Byte),
                new GenericLocationData("Break: Rending Gale", Addresses.BreakRendingGaleUnlock, "0", "192", LocationCheckType.Byte),
                new GenericLocationData("Break: Vile Scar", Addresses.BreakVileScarUnlock, "0", "192", LocationCheckType.Byte),
                new GenericLocationData("Break: Cherry Ronde", Addresses.BreakCherryRondeUnlock, "0", "128", LocationCheckType.Byte),
                new GenericLocationData("Break: Papillon Reel", Addresses.BreakPapillonReelUnlock, "0", "160", LocationCheckType.Byte),
                new GenericLocationData("Break: Sunder", Addresses.BreakSunderUnlock, "0", "192", LocationCheckType.Byte),
                new GenericLocationData("Break: Thunderwave", Addresses.BreakThunderwaveUnlock, "0", "192", LocationCheckType.Byte),
                new GenericLocationData("Break: Swallow Slash", Addresses.BreakSwallowSlashUnlock, "0", "128", LocationCheckType.Byte),
                new GenericLocationData("Break: Advent Sign", Addresses.BreakAdventSignUnlock, "0", "160", LocationCheckType.Byte),
                new GenericLocationData("Break: Mistral Edge", Addresses.BreakMistralEdgeUnlock, "0", "192", LocationCheckType.Byte),
                new GenericLocationData("Break: Glacial Gale", Addresses.BreakGlacialGaleUnlock, "0", "192", LocationCheckType.Byte),
                new GenericLocationData("Break: Killer Mantis", Addresses.BreakKillerMantisUnlock, "0", "128", LocationCheckType.Byte),
                new GenericLocationData("Break: Black Nebula", Addresses.BreakBlackNebulaUnlock, "0", "160", LocationCheckType.Byte),
                new GenericLocationData("Break: Bear Claw", Addresses.BreakBearClawUnlock, "0", "192", LocationCheckType.Byte),
                new GenericLocationData("Break: Accursed Umbra", Addresses.BreakAccursedUmbraUnlock, "0", "192", LocationCheckType.Byte),
                new GenericLocationData("Break: Iron Ripper", Addresses.BreakIronRipperUnlock, "0", "128", LocationCheckType.Byte),
                new GenericLocationData("Break: Emetic Bomb", Addresses.BreakEmeticBombUnlock, "0", "160", LocationCheckType.Byte),
                new GenericLocationData("Break: Sirocco", Addresses.BreakSiroccoUnlock, "0", "192", LocationCheckType.Byte),
                new GenericLocationData("Break: Riskbreak", Addresses.BreakRiskbreakUnlock, "0", "192", LocationCheckType.Byte),
                new GenericLocationData("Break: Gravis Aether", Addresses.BreakGravisAetherUnlock, "0", "128", LocationCheckType.Byte),
                new GenericLocationData("Break: Trinity Pulse", Addresses.BreakTrinityPulseUnlock, "0", "160", LocationCheckType.Byte),
                new GenericLocationData("Break: Bonecrusher", Addresses.BreakBonecrusherUnlock, "0", "192", LocationCheckType.Byte),
                new GenericLocationData("Break: Quickshock", Addresses.BreakQuickshockUnlock, "0", "192", LocationCheckType.Byte),
                new GenericLocationData("Break: Ignis Wheel", Addresses.BreakIgnisWheelUnlock, "0", "128", LocationCheckType.Byte),
                new GenericLocationData("Break: Hex Flux", Addresses.BreakHexFluxUnlock, "0", "160", LocationCheckType.Byte),
                new GenericLocationData("Break: Ruination Polearm", Addresses.BreakRuinationPolearmUnlock, "0", "192", LocationCheckType.Byte),
                new GenericLocationData("Break: Scythe Wind", Addresses.BreakScytheWindUnlock, "0", "192", LocationCheckType.Byte),
                new GenericLocationData("Break: Giga Tempest", Addresses.BreakGigaTempestUnlock, "0", "128", LocationCheckType.Byte),
                new GenericLocationData("Break: Spiral Scourge", Addresses.BreakSpiralScourgeUnlock, "0", "160", LocationCheckType.Byte),
                new GenericLocationData("Break: Brimstone Hail", Addresses.BreakBrimstoneHailUnlock, "0", "192", LocationCheckType.Byte),
                new GenericLocationData("Break: Heaven's Scorn", Addresses.BreakHeavensScornUnlock, "0", "192", LocationCheckType.Byte),
                new GenericLocationData("Break: Death Wail", Addresses.BreakDeathWailUnlock, "0", "192", LocationCheckType.Byte),
                new GenericLocationData("Break: Sanctus Flare", Addresses.BreakSanctusFlareUnlock, "0", "224", LocationCheckType.Byte),
                new GenericLocationData("Break: Lotus Palm", Addresses.BreakLotusPalmUnlock, "0", "192", LocationCheckType.Byte),
                new GenericLocationData("Break: Vertigo", Addresses.BreakVertigoUnlock, "0", "192", LocationCheckType.Byte),
                new GenericLocationData("Break: Vermillion Aura", Addresses.BreakVermillionAuraUnlock, "0", "128", LocationCheckType.Byte),
                new GenericLocationData("Break: Retribution", Addresses.BreakRetributionUnlock, "0", "160", LocationCheckType.Byte)
            };

            return ashleyLocations;
        }




    }
}